# Generated by Django 2.1.3 on 2018-11-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181107_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapyitem',
            name='data',
        ),
        migrations.AddField(
            model_name='scrapyitem',
            name='deal_image_url',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='scrapyitem',
            name='deal_percentage',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scrapyitem',
            name='deal_title',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='scrapyitem',
            name='web_source',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='scrapyitem',
            name='unique_id',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
