# Generated by Django 2.1.3 on 2018-11-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181111_1432'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebSource',
        ),
        migrations.AddField(
            model_name='scrapyitem',
            name='unique_id',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
