# Generated by Django 2.1.3 on 2018-11-11 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181111_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapyitem',
            name='unique_id',
        ),
    ]
